---
driver:
  name: vagrant
  synced_folders:
    - ['.', '/vagrant']
  provider: virtualbox
  customize:
    memory: 1024
    cpus: 4
    cpuexecutioncap: 50

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[zip_common::default]
    attributes:
