---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
  synced_folders:
    - ['.', '/vagrant']
  provider: virtualbox
  customize:
    memory: 1024
    cpus: 4
    cpuexecutioncap: 50

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.0
  - name: centos-6.6
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-8.1
  - name: debian-7.8

suites:
  - name: default
    run_list:
      - recipe[zip_common::default]
    attributes:
      authorization:
        sudo:
          users:
            - vagrant

