name 'zip_common'
maintainer 'Justin Alan Ryan (ZipRealty / Realogy)'
maintainer_email 'juryan@ziprealty.com'
license 'Apache 2.0'
description 'Installs/Configures zip_common'
long_description 'Installs/Configures zip_common'
version '0.2.12'

depends 'apt'
depends 'yum-epel'
depends 'users'
depends 'sudo'
depends 'hostname'
depends 'debian'
depends 'chef-client'

